### ISSUE TITLE
Publishing to the NPM registry

### ISSUE THREAD

**Issue by jeffcharles** [wapc/as-msgpack#2]
Would it be possible to publish this as a package to the NPM registry?

At the moment, it looks like I have to consume this as a git reference. Unfortunately the downside of this approach is references like version tags and even the repo itself are mutable which is potentially problematic over a longer term compared to a versioned package on the NPM registry which is much more stable.

Another pain point I've run into without this package being on the NPM registry is being unable to specify a version range for this package as a peer dependency.

**Comment by chances** [comment]
Is this not fixed? https://www.npmjs.com/package/@wapc/as-msgpack

**Comment by pkedy** [comment]
Yes! This package is now published on NPM as `@wapc/as-msgpack`. Closing this issue.
