### ISSUE TITLE
Fixnum Int Encoding / Decoding Fails With -1

### ISSUE THREAD

**Issue by dOrgJelli** [wapc/as-msgpack#6]
When encoding the value `-1` as a `i32`, it gets returned as `255` of type `u8`. I've narrowed it down to the compressed integer encoding linked below. Some tests for this would be great. You can view the tests I've created here: https://github.com/Web3-API/prototype/blob/c308796338b878140fc279aa2de5571ca88c172e/packages/wasm-as/assembly/__tests__/msgpack.spec.ts#L1-L176

Write Compressed Int:
https://github.com/wapc/as-msgpack/blob/2967753a618eb662cb46d778a85b80dd7a19f7d4/assembly/msgpack.ts#L457-L475

Write Compressed UInt:
https://github.com/wapc/as-msgpack/blob/2967753a618eb662cb46d778a85b80dd7a19f7d4/assembly/msgpack.ts#L486-L502

**Comment by pkedy** [comment]
Hi @dOrgJelli!  For tests, check out https://github.com/wapc/language-tests.  This repo tests the serialization across the languages we support. I tried replacing `math.MinInt64` and `-9223372036854775808` with `-1` and the tests passed. I'll take a look at your spec and see if I can understand what you are running into.

As a side note my next step with this is to add fuzzing which I hope will do well catching corner cases.

**Comment by pkedy** [comment]
I pulled your spec over and found the issue (I guess).  Try this tweaked `readInt64()`

```
  readInt64(): i64 {
    const prefix = this.reader.getUint8();

    if (this.isFixedInt(prefix)) {
      return <i64>prefix;
    }
    if (this.isNegativeFixedInt(prefix)) {
      return <i64>(<i8>prefix);
    }
    switch (prefix) {
      case Format.INT8:
        return <i64>this.reader.getInt8();
      case Format.INT16:
        return <i64>this.reader.getInt16();
      case Format.INT32:
        return <i64>this.reader.getInt32();
      case Format.INT64:
        return this.reader.getInt64();
      default:
        throw new Error("bad prefix for int");
    }
  }
```

Its very strange this only manifests inside as-pect.

**Comment by dOrgJelli** [comment]
This works, thanks so much @pkedy :pray:
